### PR TITLE
Add Webex Teams Cards&Buttons as native python objects

### PR DESCRIPTION
**Pull request by sQu4rks**
This PR introduces [Adaptive Cards](https://adaptivecards.io/) as native python objects. 

Example

```
from webexteamssdk.cards.card import AdaptiveCard
from webexteamssdk.cards.components import TextBlock
from webexteamssdk.cards.options import Colors, HorizontalAlignment
from webexteamssdk.cards.inputs import Text, Number
from webexteamssdk.cards.actions import Submit

title = TextBlock("Please give me your data!", color=Colors.GOOD)

first_name = Text('first_name', placeholder='Your first name')
age = Number('age', placeholder='Your age')

send_button = Submit(title='Send data')

card = AdaptiveCard(lang="en", body=[title, first_name, age], actions=[send_button])
print(str(card.to_json(pretty=True)))

```

will print the json required for this card

Screenshot 2019-10-26 at 17 14 44

### CODE REVIEW

**Comment by cmlccie** [comment]
@sQu4rks Thank you for the PR!  I apologize for the delay in getting this merged.  I am going to move the package to the `webexteamssdk.models` package and do some refactoring.

**Comment by sQu4rks** [comment]
No worries @cmlccie. I have since split this into its own package (see CiscoSE/pyadaptivecards). What do you think about adding that package as a dependency and import them in the __init__.py so that there is only one „adaptive Cards in python“ code base instead of two.

**Comment by cmlccie** [comment]
Makes sense to me!  I'll modify the webexteamssdk code to add this as an optional dependency.  If you can incorporate the `make_card_attachment(card)` function into your package, I will modify the SDK to automatically serialize the cards when passed to `WebexTeamsAPI.messages.create(attachements=)`.

**Comment by cmlccie** [comment]
@sQu4rks in case you are interested...  Here are the refactoring edits I made to the code:

https://github.com/CiscoDevNet/webexteamssdk/commit/aa0617a8404820306f5603d8c18315d0ac78084d

I agree it is better to have this functionality in a separate package that you can maintain without waiting on me.  🙂 Let me know when you have incorporated the `make_card_attachment(card)` function (or modeled attachments as python data model) and I will update the SDK to add your library as an optional dependency and integrate the automatic serialization into `messages.create()`.

Also, have you seen/used the [pydantic](https://pydantic-docs.helpmanual.io/) library?  I am increasing using this and FastAPI for projects.  It could very easily be used to model the Adaptive Cards.  I am considering using it to model the Webex Teams data models in a future release that will support Python v3 (only).  I am also thinking of migrating the library to support both synchronous and asynchronous execution in a v3 release.

**Pull request merged**
